### ISSUE TITLE
Entity Names

### ISSUE THREAD

**Issue by MrApocalyptic** [Angeschossen/UpgradeableSpawners#1]
I'm not sure if this is really a bug but when editing the entity names in the entity file it doesnt show up as that entity name on the spawner, like I changed ELDER GUARDIAN to Elder Guardian, but it still shows up as ELDER GUARDIAN on elder guardian spawners. Also would this be a good place to post suggestions/additions to the plugin? Thanks for taking your time to read this post :D

**Comment by Angeschossen** [comment]
Thanks for reporting! This is fixed in next version :)

While our Discord is in maintenance, it is fine to post suggestions here. However we do not check this very often as our majority is on Discord. Unfortunately it's currently in maintenance.
